#!/bin/bash

#--VARIABLES--
DB_ROOT_PASSWD=root
HTPASSWD_DIR=/home/ubuntu
HTPASSWD_USER=usuario
HTPASSWD_PASSWD=usuario
#--VARIABLES--

#-----------------
#Instalación pila LAMP
#-----------------

#Actualización repositorios
apt update

#Instalación apache2
apt install apache2 -y

#Instalación MySQL
apt install mysql-server -y

#Cambiar contraseña en MySQL
mysql -u root <<< "ALTER USER 'root'@'localhost' IDENTIFIED WITH caching_sha2_password BY '$DB_ROOT_PASSWD';"
mysql -u root <<< "FLUSH PRIVILEGES;"

#-----------------
#Instalación aplicación web
#-----------------

#Instalación php
apt install php libapache2-mod-php php-mysql -y 

#Configurar opciones de instalación de phpMyAdmin
echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections
echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections
echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASSWD" |debconf-set-selections
echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASSWD" | debconf-set-selections

#Instalación phpMyAdmin
apt install phpmyadmin php-mbstring php-zip php-gd php-json php-curl -y

#Clonar repositorio de la aplicación propuesta
cd /var/www/html/
rm -rf iaw-practica-lamp
git clone https://github.com/josejuansanchez/iaw-practica-lamp
mv /var/www/html/iaw-practica-lamp/src/* /var/www/html/

#Eliminamos el archivo index.html
rm -rf index.html

#Importamos el script de creación de la base de datos
mysql -u root -p$DB_ROOT_PASSWD < /var/www/html/iaw-practica-lamp/db/database.sql

#Eliminamos el contenido que no sea útil
rm -rf /var/www/html/index.html
rm -rf /var/www/html/iaw-practica-lamp

# Cambiamos los permisos
chown www-data:www-data * -R

#Instalación GoAccess
echo "deb http://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/goaccess.list
wget -O - https://deb.goaccess.io/gnugpg.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install goaccess -y

#Creación de un directorio para consultar las estadísticas
mkdir -p /var/www/html/stats
nohup goaccess /var/log/apache2/access.log -o /var/www/html/stats/index.html --log-format=COMBINED --real-time-html &
htpasswd -b -c $HTPASSWD_DIR/.htpasswd $HTPASSWD_USER $HTPASSWD_PASSWD

#Copiar archivo 000-default.conf al servidor apache
cp 000-default.conf /etc/apache2/sites-available/

#Reiniciar servicio para hacer efectivos los cambios
systemctl restart apache2
